### ISSUE TITLE
请尝试更新脚本或复制以下信息提交issue

### ISSUE THREAD

**Issue by kidddjh** [gxvv/ex-baiduyunpan#1]
请尝试更新脚本或复制以下信息提交issue
Exception: TypeError: Promise.all is not a function. (In 'Promise.all([dmPromise, gjcPromise, ddsPromise])', 'Promise.all' is undefined)
Script Ver: 0.1.2
TemperMonkey Ver: 4.3.5421
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30

**Comment by gxvv** [comment]
OSX中Safari更新TemperMonkey 后出现了这个问题，直接点击下载还是可以用的，下个版本修改

**Comment by gxvv** [comment]
已更新到0.1.3，[点击更新](https://gxvv.github.io/ex-baiduyunpan/EX-baiduyunpan.user.js)

**Comment by kidddjh** [comment]
已启动
