### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by shido520** [gxvv/ex-baiduyunpan#10]
EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue
Exception: TypeError: undefined is not a function
Script Ver: 0.1.7
TemperMonkey Ver: 2.7.3
UA: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.2000 Chrome/30.0.1599.101 Safari/537.36

**Comment by gxvv** [comment]
主要支持Chrome、Firefox和Safari的。

你的遨游浏览器的Chrome内核版本和TemperMonkey版本有点老，可以尝试更新一下你的遨游浏览器，如果不行的话只能换浏览器来使用本脚本了。
