### ISSUE TITLE
Exception: downloadManager.js加载失败  - Fixed in 0.2.2

### ISSUE THREAD

**Issue by DieHasen** [gxvv/ex-baiduyunpan#105]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

**Comment by 2cccc** [comment]
EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue
Exception: downloadManager.js加载失败
Script Ver: 0.2.1
TemperMonkey Ver: 4.6.5757
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Comment by JakeyYe** [comment]
Exception: downloadManager.js加载失败

Script Ver: 1.0.2

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
