### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by sstaroom** [gxvv/ex-baiduyunpan#114]
#Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by zb1006905653zb** [comment]
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.6.5757

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
