### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by superisePower** [gxvv/ex-baiduyunpan#116]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.3.6

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by yangqi469** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

**Comment by 523266656** [comment]
请尝试更新脚本或复制以下信息提交issue
Exception: downloadManager.js加载失败
Script Ver: 0.2.1
TemperMonkey Ver: 3.9.202
UA: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 SE 2.X MetaSr 1.0
