### ISSUE TITLE
Exception: ReferenceError: Clipboard is not defined

### ISSUE THREAD

**Issue by ichbinbz** [gxvv/ex-baiduyunpan#12]
请尝试更新脚本或复制以下信息提交issue
Exception: ReferenceError: Clipboard is not defined
Script Ver: 0.1.7
TemperMonkey Ver: 4.4
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by gxvv** [comment]
Mac OS X 10.12.6, Chrome 61未能重现。
可能是Clipboard.js没加载成功，可以稍后重试。
