### ISSUE TITLE
作者方便透露下你是怎么写出这个脚本的吗？

### ISSUE THREAD

**Issue by tarjintor** [gxvv/ex-baiduyunpan#14]
本人是搞爬虫的，平时也会去研究一些前端加密的方式，我的搞法就是自己一行行去读JS，然后搞清楚别人的算法，我刚刚看了下你的代码，感觉百度云的JS本身就非常复杂了，这么长,你也是一行行读的代码吗？

**Comment by gxvv** [comment]
百度云的js只混淆了变量名，各模块划分和逻辑还是有的。

在下载按钮上设置事件断点，然后找到下载功能用到的模块。

**Comment by YuanTianyang** [comment]
厉害了
