### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by mriderx** [gxvv/ex-baiduyunpan#146]
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.7.5788

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by zangxx66** [comment]
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

同样的问题
