### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by arong-me** [gxvv/ex-baiduyunpan#158]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by baibai-lee** [comment]
Exception: downloadManager.js加载失败
Script Ver: 0.2.1
TemperMonkey Ver: 4.6
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.4549.400 QQBrowser/9.7.12918.400

类似的issue
