### ISSUE TITLE
这

### ISSUE THREAD

**Issue by wangxiangwei008** [gxvv/ex-baiduyunpan#16]
Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.5.5648

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by gxvv** [comment]
FF&TM测试没问题，可能是网络问题，请重试几次。
