### ISSUE TITLE
百度貌似已经升级原先的所有脚本和chrome插件都已失效

### ISSUE THREAD

**Issue by KyonCN** [gxvv/ex-baiduyunpan#165]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.

**Comment by gxvv** [comment]
我这没问题，更新浏览器、TamperMonkey、脚本
<img width="201" alt="image" src="https://user-images.githubusercontent.com/8492441/41910060-3027f97a-797b-11e8-9f66-1771715f2521.png">
