### ISSUE TITLE
复制链接时出错

### ISSUE THREAD

**Issue by yuquanguo** [gxvv/ex-baiduyunpan#17]
Exception: TypeError: Illegal constructor

Script Ver: 0.1.7

TemperMonkey Ver: 4.4

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by gxvv** [comment]
相同环境测试没有问题。似乎是由于没用成功加载Clipboard.js造成的。请换个时间再试下。
