### ISSUE TITLE
downloadManager.js加载失败

### ISSUE THREAD

**Issue by liuhongchen** [gxvv/ex-baiduyunpan#170]
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by lightasalt** [comment]
同样的问题,何解?
