### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by lqz8** [gxvv/ex-baiduyunpan#172]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.
Script Ver: 0.1.6

TemperMonkey Ver: 4.4

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by pcmid** [comment]
# the same exception
```
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
```
