### ISSUE TITLE
Mac下尝试复制链接直接调用迅雷

### ISSUE THREAD

**Issue by haycarol** [gxvv/ex-baiduyunpan#18]
Mac下尝试复制链接直接调用迅雷，不弹对话框，但是选择多文件的时候，链接不知道怎么处理，有时间交流一下。谢谢

**Comment by gxvv** [comment]
提供下思路：

1.  打开迅雷的剪贴板监听
2. 注释掉[L229](https://github.com/gxvv/ex-baiduyunpan/blob/master/EX-baiduyunpan.user.js#L229)到[L260](https://github.com/gxvv/ex-baiduyunpan/blob/master/EX-baiduyunpan.user.js#L260)
3. 使用[GM_setClipboard](http://tampermonkey.net/documentation.php?ext=dhdg#GM_setClipboard)将链接复制到剪贴板

### ❓ 问题
* `GM_setClipboard `似乎兼容性有些问题，是否能正常工作请自己尝试。
* 百度云返回的链接不能正确触发迅雷的监听，可以通过每个链接后加上`&.zip`触发。 :unamused:

**Comment by haycarol** [comment]
感谢回复，开始尝试使用thunder://调用迅雷，后来因为多个连接没办法识别换行，后来改用转换thunder协议的url，然后复制到剪贴板中，成功了。然后最近百度有动作，复制的地址不能用了，请问有没有时间修复呢？另外，有没有可能再增加按钮或者把这部分代码合并到主分支上呢？

**Comment by haycarol** [comment]
1.关于迅雷监听剪贴板
开始使用插件的时候，复制剪贴板，迅雷不识别，但是一些代码文件名的是可以识别的，后来猜测，生成url里面没有能够识别的文件名，所以没办法识别，后来根据一款软件得来思路，转换成thunder://的地址，迅雷就自动识别了。关于多行地址，放入剪贴板的时候，多个url用\n拆分一下，迅雷也可以自动识别。
var t_links=[];
for(var i in dlinks){
    var url= dlinks[i];
    var t_url = ThunderEncode(url);
    t_links.push(t_url);
}
GM_setClipboard(t_links.join('\n'), 'text');
2.关于复制的地址
确实很遗憾，地址在浏览器中是可以下载的，在迅雷中，貌似被限制了，我的迅雷使用vip的，以前下载基本不限速。
