### ISSUE TITLE
同时下载多个文件，发送到远程服务器的文件命名会打乱顺序

### ISSUE THREAD

**Issue by 1149663712** [gxvv/ex-baiduyunpan#181]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.
我在下载番剧时发现，发送到远程服务器下载的文件与百度网盘的不匹配，单个下载是没问题的，就是批量下载时会出现文件名与度盘的不符(就是一个100M的A文件和一个300M的B文件，批量导出下载链接发送过去就变成了100M的B文件和300M的A文件了)，这导致我下了好几部番，每一集都得先看是第几集，再重命名文件（无奈.jpg）

**Comment by gxvv** [comment]
获取压缩链接的时候吗？

**Comment by frankmm** [comment]
发送到aria2，比如3集电视剧，文件名和文件错乱，比如第一集用了第三集的文件名，特别是下载游戏压缩包的时候，完全无法分辨哪个是哪个。

**Comment by gxvv** [comment]
@frankmm 
选中的全部都是文件吗？使用的是复制链接还是复制压缩链接？

**Comment by frankmm** [comment]
多个文件选中后，复制链接，然后发送到aria2就会这样，好几个插件都是基于你这个的，都有这个问题。https://greasyfork.org/zh-CN/forum/discussion/40046/x

**Comment by gxvv** [comment]
看了下这个脚本，感觉在传递给aria2的时候，处理链接和文件名的方式似乎有点问题。🧐

和我没关系。
