### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by aeeq** [gxvv/ex-baiduyunpan#182]
EX-baiduyunpan:程序异常

请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.7.5788 

UA: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by aeeq** [comment]
升级到 最新版就行了

**Comment by xianghongai** [comment]
```
EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue
Exception: downloadManager.js加载失败
Script Ver: 0.2.1
TemperMonkey Ver: 4.7.5788
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
```
