### ISSUE TITLE
请问还会更新新版吗？一直都不能使用

### ISSUE THREAD

**Issue by love19791126** [gxvv/ex-baiduyunpan#184]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.

**Comment by gxvv** [comment]
最新版[0.3.1](https://github.com/gxvv/ex-baiduyunpan/raw/master/EX-baiduyunpan.user.js)，同时关闭其他脚本

> 仅对最新版Chrome和Safari浏览器下TamperMonkey提供支持
