### ISSUE TITLE
Exception: downloadManager.js加载失败  Script Ver: 2018.04.04_0.2.1.Mod  TemperMonkey Ver: 4.6  UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

### ISSUE THREAD

**Issue by ArgusFH** [gxvv/ex-baiduyunpan#185]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by JYeung111** [comment]
The Script Ver: 2018.04.04_0.2.1.Mod is the copy-cat version (https://greasyfork.org/zh-CN/scripts/39854) which published by "yi ming". In case of any problem, that should be going back to that script publisher and ask.
Why come here and ask.

**Comment by gxvv** [comment]
@JYeung111 Thanks you for your reply.
Because the script reserves my `@supportURL` and the issue's link in dialog. 

I'm boring to reply the same issues.
To fix this problem needs to uninstall the modified script at first, otherwise my script is still not working.
