### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by shetz163** [gxvv/ex-baiduyunpan#188]
点击普通下载之后无法获取到资源链接,
看了一下报错是一个关于 update.pan.baidu.com/statistics 的链接报502了,
之后用来请求下载链接 d.pcs.baidu.com/file/ 的字段报403,
error_msg 写的是 user is not authorized, hitcode:116,
![image](https://user-images.githubusercontent.com/5582519/42800695-74137db2-89cf-11e8-8fff-7fc65f15ba12.png)

不知道是我用的方法不对还是百度已经堵上了这个方法了

**Comment by gxvv** [comment]
下载403返回和下载工具有关。502这个接口没用的。可以试下复制压缩链接。

**Comment by shetz163** [comment]
发现问题是什么了,视频的外链有问题,无论是下载压缩包还是原始文件,都无法下载,不知道是因为什么,以及现在百度方面限得好死啊,现在下载速度最多500kb/s了,下个10G的电影得下大半天,无奈

**Comment by JYeung111** [comment]
To  shetz163 
速度問題 500kb/s！這不是腳本的問題，只要提供下載鏈接便算完成任務，至於速度可達那水平，就要視乎你運用下載器的技巧！
吾信就看附圖，
![sam3](https://user-images.githubusercontent.com/41117798/42818505-a513e7c4-8a03-11e8-9469-86c9265fb79f.PNG)
圖中的下載表現是由一台老太爺級win-XP機提供。

**Comment by shetz163** [comment]
是多线程的问题么?我一直都是500kb/s的速度,还是是因为我useragent没设置对呢?希望可以得到解答
