### ISSUE TITLE
error chrome

### ISSUE THREAD

**Issue by prokiller1199** [gxvv/ex-baiduyunpan#189]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.

**Comment by JYeung111** [comment]
To prokiller1199
你用的是yi.ming的抄襲版，有問題就應問抄襲者。

**Comment by prokiller1199** [comment]
那怎样用你的

**Comment by JYeung111** [comment]
我用的是自家重寫改良版，當然是運作暢順無阻；如果想要有作者的支援就不要用抄襲版，應該立即删除這些抄襲腳本，重新安裝最新原創版 V.0.3.2；因這版本使用新句法，所以對用家Browser和TM 有要求，如不能有效運作，可改用次級v.0.2.2版。

**Comment by prokiller1199** [comment]
好的 我现在去卸载
