### ISSUE TITLE
can't download from paidu   please help

### ISSUE THREAD

**Issue by hemazone** [gxvv/ex-baiduyunpan#19]
hello ,

wen i tried to use  EX-百度云盘    it was working  100 %    but  now  its  not  
cannot download  and  gives me this messge

{"error_code":31326,"error_msg":"anti hotlinking , hitcode:113","request_id":493048889170548034}

**Comment by gxvv** [comment]
It works for me. Try it later.

According to the response, you trigger the anti hotlinking mechanism of Baidu. Don't request the download link frequently and high-concurrently.

If the question is persiste, please provide more information (browser, system & their versions).

**Comment by speakermids** [comment]
Hi,
I'm facing the hotlinking issue too. It's been a week.
Need help :(

**Comment by hemazone** [comment]
> If the question is persiste, please provide more information (browser, system & their versions). 
its still same and the problem still exist   ::(
i'm  using  windows 10 pro    +   google chrome  Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by gxvv** [comment]
@hemazone @speakermids 

The problem doesn't appear on my browser (win7 64bit&chrome, Mac&safari&chrome). And this problem is because of the Baidu Server. I don't know the detail of that.

Which type of url is you download page(Home page: `https://pan.baidu.com/disk/home` or Share page: `https://pan.baidu.com/share/link`)? I suggest your to save the files to your own BaiduYun and then try download it again.

**Comment by speakermids** [comment]
@gxvv  Mostly, this type of links 
https://pan.baidu.com/s/1jGNWvt0
pw : bbw7

To be honest, I don't have any baidu account. Its complicated to register.

**Comment by hemazone** [comment]
i use links like  this   (  https://pan.baidu.com/s/1pLVfA23     )    and it was working 100 %   before 
now it wont ,   all links like this   also  not working  
and  registration to baidu is very hard    :(

**Comment by gxvv** [comment]
<img width="656" alt="screen shot 2018-01-23 at 10 53 00 pm" src="https://user-images.githubusercontent.com/8492441/35318107-e5122214-0114-11e8-8b7c-1d1d8fa1a486.png">

I can't reproduce this problem and without login either.

It might be a network problem. Are you in China?

**Comment by speakermids** [comment]
I'm in singapore. 
It was working very fine last few weeks though.

**Comment by gxvv** [comment]
Do you install some other scripts or browser plugins?

It seems that the BaiduYun is  begin to limit some third part plugins and softwares. This error message isn't due to my script.

About your question, I only have one last idea that try configure a Chinese proxy ... :sweat_smile:

**Comment by speakermids** [comment]
@gxvv Only script running on browser are adsbypasser,adblock and your script only.

**Comment by jack980517** [comment]
Seems to be a server-side restriction imposed since several days ago: http://www.panduoduo.net/help/5
Other Chinese users also reported that they can only download from Baidu Netdisk when logged in.

**Comment by speakermids** [comment]
Hope this can fix asap :D!

**Comment by speakermids** [comment]
Hi!
I just wanted to say, I think its okay now (for now maybe)
I just downloaded 3gb worth of file

**Comment by gxvv** [comment]
It would appears randomly. Getting an account will be more reliable. 😃
