### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ioudove** [gxvv/ex-baiduyunpan#191]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.
**请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36**

**Comment by JYeung111** [comment]
TO  ioudove:

你用的是yi.ming的抄襲版，有問題就應問抄襲者。

![ex-copy-cat](https://user-images.githubusercontent.com/41117798/42949490-718b8ee6-8ba4-11e8-834d-f37fc846be70.PNG)

如果想要有作者的支援就不要用別人的抄襲版，應該立即卸载這些抄襲腳本，重新安裝
最新原創版後，再有問題先來此求救！

**Comment by ioudove** [comment]
原版的链接给下

________________________________
发件人: JYeung111 <notifications@github.com>
发送时间: 2018年7月19日 14:43:58
收件人: gxvv/ex-baiduyunpan
抄送: ioudove; Author
主题: Re: [gxvv/ex-baiduyunpan] bug (#191)


TO ioudove:

你用的是yi.ming的抄u版，有}就抄u者。

[ex-copy-cat]<https://user-images.githubusercontent.com/41117798/42949490-718b8ee6-8ba4-11e8-834d-f37fc846be70.PNG>

如果想要有作者的支援就不要用e人的抄u版，立即卸载@些抄u_本，重新安b
最新原版後，再有}先泶饲缶龋

―
