### ISSUE TITLE
Exception: downloadManager.js fail

### ISSUE THREAD

**Issue by xiaoaozqd** [gxvv/ex-baiduyunpan#193]
Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.3.6

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by fefsaxoap** [comment]
请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.7.5788

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
