### ISSUE TITLE
Chrome浏览器

### ISSUE THREAD

**Issue by orangbus** [gxvv/ex-baiduyunpan#195]
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3486.0 Safari/537.36

**Comment by JYeung111** [comment]
To orangbus:

你用的是yi.ming的抄襲版，有問題就應問抄襲者。

如果想要有作者的支援就不要用別人的抄襲版，應該立即卸载這些抄襲腳本，重新安裝
最新原創版後，再有問題先來此求救！
