### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by debugbb** [gxvv/ex-baiduyunpan#197]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by debugbb** [comment]
没有说明，直接关了？

**Comment by zgr0629** [comment]
https://gxvv.github.io/ex-baiduyunpan/EX-baiduyunpan.user.js

**Comment by zgr0629** [comment]
现在已经是0.3.3了，点上面的链接更新一下。
