### ISSUE TITLE
百度企业网盘网页版打开报错

### ISSUE THREAD

**Issue by hundan2020** [gxvv/ex-baiduyunpan#199]
不知道是不是支持百度企业网盘的，但是今天进入企业网盘的时候，这个插件启用了，而且报了错。
已经是最新版脚本。
`pan.baidu.com`正常加载。

## 复现网址 

`https://eyun.baidu.com/enterprise/index`

## 报错内容 

```
Exception: Error: 插件加载失败 core crack failed

Script Ver: 0.3.2

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
```

![image](https://user-images.githubusercontent.com/9510938/43717942-b22289a8-99bb-11e8-9bfe-a9dc5e36d9d7.png)

**Comment by gxvv** [comment]
我没有企业网盘，只调试过分享页是可以的，后面会把这个 `URL` 给屏蔽一下。

**Comment by 15040941306** [comment]
![default](https://user-images.githubusercontent.com/32926331/44032554-00837d72-9f3a-11e8-9db0-d476ed13fc04.png)
这个是我的，pan.baidu.com报错
