### ISSUE TITLE
插件好像失效了。

### ISSUE THREAD

**Issue by ywltby** [gxvv/ex-baiduyunpan#20]
向上几张截图：
![1](http://ww4.sinaimg.cn/large/0060lm7Tly1fnrxaxeij2j313r0c1juk.jpg)
![2](http://ww4.sinaimg.cn/large/0060lm7Tly1fnrxbo0jttj30ei06f74b.jpg)
![3](http://ww4.sinaimg.cn/large/0060lm7Tly1fnrxc9v4n0j30h808274w.jpg)
![4](http://ww4.sinaimg.cn/large/0060lm7Tly1fnrxcjxt3dj309a064jrf.jpg)
第一张图是控制台截图，其他的就是我的操作流程，之前我这样做是没问题的，可现在就如图4所示了，还希望作者尽快解决~不胜感激！

**Comment by ywltby** [comment]
下载工具是IDM

**Comment by gxvv** [comment]
浏览器可以直接下载吗？网上看到有人说百度禁止了IDM和迅雷下载，放到文件夹里再下载好像可以的

**Comment by ywltby** [comment]
用浏览器下载的速度和不用插件下载的速度是一样的。
（第一个是直接下载，不用插件，第二个是用插件在浏览器下，如图）


在2018年1月24日 19:48，gxvv<notifications@github.com> 写道：

浏览器可以直接下载吗？网上看到有人说百度禁止了IDM和迅雷下载，放到文件夹里再下载好像可以的

**Comment by ywltby** [comment]
这样的话就没什么意义了，不如直接下了。
在2018年1月24日 19:51，ysy1365898936<ysy1365898936@163.com> 写道：


用浏览器下载的速度和不用插件下载的速度是一样的。
（第一个是直接下载，不用插件，第二个是用插件在浏览器下，如图）


在2018年1月24日 19:48，gxvv<notifications@github.com> 写道：

浏览器可以直接下载吗？网上看到有人说百度禁止了IDM和迅雷下载，放到文件夹里再下载好像可以的

**Comment by gxvv** [comment]
浏览器中能下的话，说明获取到的链接没问题，问题出在IDM里。我不用IDM，试下EagleGet。

**Comment by ywltby** [comment]
用“复制链接”会出现下面第二个的情况：


用“普通下载”浏览器弹出下载后把链接复制之后下载会出现第二个情况
在2018年1月24日 20:01，gxvv<notifications@github.com> 写道：

浏览器中能下的话，说明获取到的链接没问题，问题出在IDM里。我不用IDM，试下EagleGet。

**Comment by ywltby** [comment]
用Google Chrome得到的结果也一样。




在2018年1月24日 20:15，ysy1365898936<ysy1365898936@163.com> 写道：


用“复制链接”会出现下面第二个的情况：


用“普通下载”浏览器弹出下载后把链接复制之后下载会出现第二个情况
在2018年1月24日 20:01，gxvv<notifications@github.com> 写道：

浏览器中能下的话，说明获取到的链接没问题，问题出在IDM里。我不用IDM，试下EagleGet。

**Comment by gxvv** [comment]
最近出现迅雷、IDM、Aria2无法下载，返回403错误，应该是由于百度对下载工具进行了限制。现在从脚本上是无法解决这个问题的。

**Comment by ywltby** [comment]
好的，我明白了，谢谢你了~
在2018年1月24日 22:25，gxvv<notifications@github.com> 写道：

最近出现迅雷、IDM、Aria2无法下载，返回403错误，应该是由于百度对下载工具进行了限制。现在从脚本上是无法解决这个问题的。
