### ISSUE TITLE
打开百度企业网盘页面时报错

### ISSUE THREAD

**Issue by snooby2333** [gxvv/ex-baiduyunpan#204]
复现地址：https://eyun.baidu.com/s/3pLMbUqR
错误信息：
Exception: Error: Cannot find module `system-core:context/context.js`
Script Ver: 0.3.2
TemperMonkey Ver: 4.7
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by JYeung111** [comment]
百度企業分享版於月前作出一些改動，prefix改動 是其中一項，因此所有 EX-百度云盘或衍生版均會對企業分享版一律失效，直至作出相關修正。
