### ISSUE TITLE
取消提交issue的link链接

### ISSUE THREAD

**Issue by woeijiunn88** [gxvv/ex-baiduyunpan#205]
感觉你写了 “请不要提交重复issue”，但这里太多重复性的issue了，导致这里满满的“垃圾”issue。
建议把“提交issue”的link拿掉比较好，让知道github的用户亲自来这里提交issue。

**Comment by gxvv** [comment]
你说的没错，我也很后悔放了这个链接。:frowning_face:

**Comment by mu228** [comment]
感谢大佬的脚本.

**Comment by woeijiunn88** [comment]
看您自己决定要不要移除掉咯～
等待下个版本:flushed:

**Comment by abc747543545** [comment]
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
