### ISSUE TITLE
部分页面无法运行

### ISSUE THREAD

**Issue by linxingwu** [gxvv/ex-baiduyunpan#208]
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by JYeung111** [comment]
The Script Ver: 2018.04.04_0.2.1.Mod is the copy-cat version (https://greasyfork.org/zh-CN/scripts/39854) which published by "yi ming". In case of any problem, that should be going back to that script publisher and ask.
This issue can be closed directly
