### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xiangsanliu** [gxvv/ex-baiduyunpan#21]
Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by gxvv** [comment]
Duplicate of #9
