### ISSUE TITLE
文件名的url编码问题

### ISSUE THREAD

**Issue by Yun-Shan** [gxvv/ex-baiduyunpan#210]
下载的文件如果名字带空格的，空格会变成+号。
在极少数情况下(正好被我碰到了)，直接解压 然后其它程序处理的时候经过url解码，会将+号解析成空格从而导致找不到文件。
由于只有通过这个插件下载的文件才有文件名变成+号导致的这个问题，因此在网上找不到解决方案，我搞了好久才发现是这个的原因。
建议下载时对文件名进行url解码 以保证下载的文件名和原始的文件名一致

**Comment by gxvv** [comment]
能把操作描述得详细一点吗？
是通过复制压缩链接来下载文件名中带空格的文件，还是下载一个文件夹，文件夹里包含有文件名带空格的文件？
问题是发生在下载工具中，还是压缩软件？

**Comment by Yun-Shan** [comment]
是下载文件名带空格的文件。是直接点的下载，没有点复制链接和复制压缩链接，单纯的下载。
它是在一个网盘文件夹里面，然后有一列文件，鼠标悬停在某个文件上就会有下载的图标，在那里直接点的下载。
网盘里本身是压缩文件，比如网盘里的文件是 `1 2.zip` 直接点的下载 下载下来的就是 `1+2.zip`，然后我直接解压得到的就是一个`1+2`的文件夹

因为是一个游戏的程序然后它会解析自己的路径，但是它又有个url解码 结果就出事了

浏览器是Chrome 67.0.3396.99（正式版本） （64 位）

**Comment by Yun-Shan** [comment]
自己上传了一个小压缩包测试了一下 没有这个问题。可能是因为大压缩包要绕过网盘强行打开客户端而使用直链导致的问题
这是我下载出事的网盘的地址
https://pan.baidu.com/s/1kVpvW8J

**Comment by gxvv** [comment]
试了一下，确实是有这样的问题。
点击下载的时候使用的链接和复制链接中的链接是相同的。
同一个链接，浏览器自带的下载会导致空格转换成`+`号，我试了一下迅雷和 aria2c，都是不会有`+`号的。
建议你使用下载工具下载试试。

**Comment by Yun-Shan** [comment]
我试了一下文件名是1+2的时候 用插件+浏览器下载就变成了1%2B2
可以考虑对下载的文件名进行url解码吗

**Comment by Yun-Shan** [comment]
看了一下网络请求
小文件的是
`Content-Disposition: attachment;filename="1+2"`
`Content-Disposition: attachment;filename="1 2"`
大文件是
`Content-Disposition: attachment;filename=1%2B2` 
`Content-Disposition: attachment;filename=1+2`

是下载链接经过百度302之后的实际下载链接_(:з」∠)_有希望改吗

**Comment by gxvv** [comment]
我使用 curl 试了下，经过两次重定向之后得到的 header
<img width="499" alt="image" src="https://user-images.githubusercontent.com/8492441/45129195-e80a0300-b1b4-11e8-9599-7e804e4049d6.png">

我觉得会出现上面的情况应该是浏览器的问题，无法解决

**Comment by JYeung111** [comment]
如果調用外置下載器例如 eagleget 或 proxyee-down等，問題是可以解决！

2018-09-11
今天再測試，文件名問題己經是解决，可能百度做了些改動吧！
