### ISSUE TITLE
对火狐手机版的支持

### ISSUE THREAD

**Issue by thanksshu** [gxvv/ex-baiduyunpan#213]
火狐手机版支持脚本了，有方法使这个支持手机吗？谢谢了。

**Comment by gxvv** [comment]
没有支持火狐的计划

**Comment by JYeung111** [comment]
此腳本基本上是可以在 火狐+TamperMonkey或暴力猴上全面性運作，只需作少量改動便可以，
我就是使用 Firfox52+TM4.5 (而Firfox52+暴力猴2.9.6 則新加入作試用，初步結果是需更少的改動)，腳本 運作正常‧

如配用GM3則改動會很大
