### ISSUE TITLE
压缩链接有限制了 ?

### ISSUE THREAD

**Issue by aeeq** [gxvv/ex-baiduyunpan#215]
压缩链接有限制了 ? 下载 1.3 G 文件提示
{"error_code":31090,"error_msg":"package is too large"}

**Comment by gxvv** [comment]
未发现该问题，可能是个别资源的问题。该问题无法解决。

**Comment by cailurus** [comment]
同有限制
{"error_code": 31090, "error_msg": "package is too large", "request_id": 5913555496460099000}
