### ISSUE TITLE
求支持暴力猴啊

### ISSUE THREAD

**Issue by aunsen** [gxvv/ex-baiduyunpan#217]
TM越来越臃肿，清爽的暴力猴现在用的人也是越来越多，这个度盘的脚本也是使用多年不能舍弃的，希望作者能支持暴力猴，再次感谢！

**Comment by gxvv** [comment]
可是这个不支持 Safari。。。

**Comment by aunsen** [comment]
没有其他的办法了么，或者说只能指望暴力猴支持Safari？

**Comment by JYeung111** [comment]
方法當然有，最簡單是改用另一個腳本
syhyz1990 修改的 "百度网盘直接下载助手"  v.1.2.3
當然那個結構原始，而又非原作，支援力會少點。
另一個是自行修改和替換此腳本中那些不被暴力猴支援的句碼，
此腳本所用指令句碼原是本有部份不被本人老版機支援，
早前成功改寫到支援GM3後，錯誤地全刪除，真失敗。

**Comment by aunsen** [comment]
我火狐64夜版+暴力猴，"百度网盘直接下载助手" v.1.2.3还是最新的1.2.5都不行，都还是要调用客户端下载，真的是郁闷死了，真的不想用回TM，要疯了......

**Comment by JYeung111** [comment]
百度网盘直接下载助手 腳本不會改動百度本身的下載按鈕，不會要求用家使用此按鈕，為何會按它而引發调用客户端下载，兩個腳本的操作是有些不同，有附圖為証，注意紅圈，要變通一些吧！
![v1](https://user-images.githubusercontent.com/41117798/45486907-4fb0e700-b78f-11e8-9ac6-b24b0e364075.PNG)
![v2](https://user-images.githubusercontent.com/41117798/45486910-50e21400-b78f-11e8-8f4a-eb5fe1b71fc4.PNG)
再者我個人認為v1.2.5有些不穩妥！

**Comment by aunsen** [comment]
谢谢，只能曲线救国拷贝链接后再下载了，另外吐槽一下上古xp和FF...

**Comment by JYeung111** [comment]
古代人當然用遠古的系統：
WinXP 32Bit 
Firefox52 ESR 
GM3.17+TM4.5+VM2.9.6(for testing only)

**Comment by aunsen** [comment]
真大神才不在乎什么系统，大神有空了出个EX度盘的暴力猴版本吧......

**Comment by JYeung111** [comment]
EX度盘的暴力猴版本
是很容易做的版本，初步測試是比GM版本容易很多，它所支援的句法比較接近TM，
如果無需功能提升和破解壓縮容量300MB限制，初版已有！！！

**Comment by aunsen** [comment]
既然如此那我还是小小的奢望一把暴力猴版本吧...

**Comment by JYeung111** [comment]
不想給那些無品抄襲者，佔完便宜後更罵人，我己多次領教，自此以後，所以不會再公開發放我的百度作品，如想要請在 greasyfork.org 論壇中給我 (JYeung) 私信，稍後自會發放下載鏈接！

**Comment by aunsen** [comment]
这样的人我是早就见怪不怪了，话说 greasyfork.org 论坛怎么私信啊...

**Comment by JYeung111** [comment]
己在 greasyfork.org 論壇中 私信回覆
是百度分享!!!
