### ISSUE TITLE
程序异常

### ISSUE THREAD

**Issue by KevinChance** [gxvv/ex-baiduyunpan#218]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by Puppeteer-Hao** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3514.0 Safari/537.36

**Comment by JYeung111** [comment]
這是舊版，請更新腳本
最新版是 Script Ver: 0.3.3
