### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by AlmMn** [gxvv/ex-baiduyunpan#219]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.8.5850

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by JYeung111** [comment]
這是舊版，請更新腳本
最新版是 Script Ver: 0.3.3

**Comment by sotd-of** [comment]
Exception: TypeError: Cannot read property 'tip' of undefined

Script Ver: 0.3.3

TemperMonkey Ver: 4.8.5898

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
