### ISSUE TITLE
获取的文件夹下载链接无法使用

### ISSUE THREAD

**Issue by rubyKC** [gxvv/ex-baiduyunpan#220]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.

[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed

**Comment by JYeung111** [comment]
只要是打包式下載而其總容量(total file size)超過３００ＭＢ左右就會被拒絕！這是百度新加在伺服器進行壓縮時可使用的工作空間容量限制。
其他就暫時維持正常！

Error message 是
{"error_code":31090,"error_msg":"package is too large","request_id":5907165406226159388}

這是很難突破的限制，只能避開

**Comment by share18x** [comment]
妈耶，打包下载不行了，被限速で好惨

**Comment by JYeung111** [comment]
打包下载被限速，就用直接下載，一樣可達合理可接受速度(MB/s)，方法有很多種，亦有部份己公開發放多月，只是人人懶得去找，查閱。加上有些無品抄襲者只會copy 又會罵人，有方法都不會公開，我是其中一位小氣人，哈哈！
不過我就萬分欣賞 gxvv 的宏大氣量。

**Comment by gxvv** [comment]
@JYeung111 
哈哈，开源的东西肯定是这样的，没办法的，生气不值得。:smile:
