### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by Xiantongc612** [gxvv/ex-baiduyunpan#222]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed

**Comment by CristinaTAT** [comment]
我这也是同样的问题

**Comment by JYeung111** [comment]
版本太舊，請先更新版本後再試！

提交问题 前，请 **查看** 是否有 **相同** 的 Issue !!!!
