### ISSUE TITLE
js加载失败

### ISSUE THREAD

**Issue by JXC321** [gxvv/ex-baiduyunpan#223]
Exception: downloadManager.js加载失败

Script Ver: 2018.03.24_0.3.1Mod

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by JYeung111** [comment]
JXC321 使用不 作者gxvv 的原版，而是抄襲者(copy-cat) 的作品！
一是向抄襲者提問，另一新是重新安裝原作后再試！
