### ISSUE TITLE
火狐浏览器打开百度盘后，弹框提示ex插件加载成功，弹出后不自动消失，导致浏览器卡死

### ISSUE THREAD

**Issue by junlovejing** [gxvv/ex-baiduyunpan#224]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.

[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed

**Comment by JYeung111** [comment]
火狐浏览器打开百度盘后，弹框提示ex插件加载成功，弹出后不自动消失
-- 是正常
浏览器卡死，最大可能性同使多個 Ex 的複制版，而加上不同一版号，由加載先後，混雜不同版本的define function，而且是相同prefix，當出現 互相呼叫，會令相关全部腳本失效，如腳本失控有機會 loop 死該 tabs，早前曾做過這試驗，亦指出這問題，因該copy cat是使用別的名 xxx下載助手，而內容則是EX 腳本，結果招copy-cat指罵，理由是這開放版，他有權想點都得。
如無其他詳細資訊，此case 可以closed。
