### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by ColsonRichard** [gxvv/ex-baiduyunpan#225]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by JYeung111** [comment]
版本太舊，請先更新版本後再試！
