### ISSUE TITLE
Exception: downloadManager.js加载失败 Script Ver: 0.2.1 TemperMonkey Ver: 4.7 UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 UBrowser/6.2.4094.1 Safari/537.36

### ISSUE THREAD

**Issue by ChrisLeeJW** [gxvv/ex-baiduyunpan#226]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.

[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed

**Comment by JYeung111** [comment]
版本太舊，請先更新版本後再試！
