### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by feiyefeiye** [gxvv/ex-baiduyunpan#227]
Exception: downloadManager.js加载失败

Script Ver: 2018.03.24_0.3.1Mod

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by JYeung111** [comment]
To: feiyefeiye  
你正使用的不 是作者gxvv 的原版，而是抄襲者(copy-cat) 的作品！
一是向抄襲者提問，另一新是重新安裝原作后再試！
再者亦是舊的抄襲版！
