### ISSUE TITLE
希望支持手机版网页

### ISSUE THREAD

**Issue by liangsai12** [gxvv/ex-baiduyunpan#228]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.

[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed

**Comment by gxvv** [comment]
不会支持
