### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by gggitpl** [gxvv/ex-baiduyunpan#233]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36

**Comment by JYeung111** [comment]
這是舊版，請更新腳本
最新版是 Script Ver: 0.3.3

**Comment by Justsoos** [comment]
油猴里版本并未更新，目前是：
```
// @name         EX-百度云盘修改版
// @namespace    https://github.com/gxvv/ex-baiduyunpan/
// @supportURL   https://github.com/gxvv/ex-baiduyunpan/issues
// @version      2018.04.04_0.2.1.Mod
// @date         01/01/2017
// @modified     04/04/2018
// @author       gxvv、zd423、网友们
// @license      MIT
```
实际去搜了下，在 https://greasyfork.org/ 里已经消失了。。。

**Comment by Justsoos** [comment]
反而发现搜索排第一的，是抄袭了本站代码的这个：
https://greasyfork.org/zh-CN/scripts/369221-%E7%99%BE%E5%BA%A6%E4%BA%91%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B%E7%9B%B4%E9%93%BE%E5%8A%A0%E9%80%9F%E7%89%88%E6%94%AF%E6%8C%81%E8%BF%85%E9%9B%B7-vip%E8%A7%86%E9%A2%91%E5%9C%A8%E7%BA%BF%E8%A7%A3%E6%9E%90%E7%A0%B4%E8%A7%A3%E5%8E%BB%E5%B9%BF%E5%91%8A-%E5%A4%A7%E9%A2%9D%E4%BC%98%E6%83%A0%E5%88%B8%E5%9B%BD%E5%BA%86%E6%8D%A2%E6%96%B0-%E9%A2%86%E5%8F%96%E6%94%AF%E4%BB%98%E5%AE%9D%E7%B4%85%E5%8C%85-%E6%B7%98%E5%AE%9D%E5%A4%A9%E7%8C%AB%E9%9A%90%E8%97%8F%E4%BC%98%E6%83%A0%E5%88%B8-%E8%B4%AD%E7%89%A9%E7%AB%8B%E7%9C%8180-%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%85%A8%E6%96%B0%E6%8E%A8%E5%87%BA-2018-9-29%E5%8A%A0%E5%BC%BA%E7%A8%B3%E5%AE%9A%E7%89%88

**Comment by Justsoos** [comment]
找到本站油猴项目了。https://greasyfork.org/zh-CN/scripts/26638-ex-%E7%99%BE%E5%BA%A6%E4%BA%91%E7%9B%98

但实用发现一个bug，一个目录内有300多mp3文件，搜索 "mp3" 后出现的chrome窗口上使用“复制链接”，只能复制出30个下载链接。

另打开一个600文件目录，页面拉到最下，复制链接，实际复制出来45个链接。

**Comment by gxvv** [comment]
@Justsoos 
一次请求过多的文件经常会有一些请求无法正确返回，导致缺少链接了。

**Comment by JYeung111** [comment]
很久曾做测試，頁面所記載只能100 項，向百度查詢是每次回應亦不超100項資訊(record)，至查詢己點選的文件就不太記得，好似更少。加上量超多會引發記憶溢出問題，要明白每一文伴行所需記憶體比你見得到一行字多出百倍，就單一個下載鏈長度由數百至近千字，如果要處數以百計文件的下載模式，如果係MP3這類小文件，可用分頁打包式下載，只要控制每次300M以下就可以；否則就應用外置獨立程式(program) ，
再者這類限制是趨向收緊。

**Comment by gxvv** [comment]
> 很久曾做测試，頁面所記載只能100 項，向百度查詢是每次回應亦不超100項資訊(record)，至查詢己點選的文件就不太記得，好似更少。加上量超多會引發記憶溢出問題，要明白每一文伴行所需記憶體比你見得到一行字多出百倍，就單一個下載鏈長度由數百至近千字，如果要處數以百計文件的下載模式，如果係MP3這類小文件，可用分頁打包式下載，只要控制每次300M以下就可以；否則就應用外置獨立程式(program) ，
再者這類限制是趨向收緊。

单页默认显示 100 项，滚动到底部后加载后 100 项。

同时请求的链接上限，似乎是浏览器的限制。即便接口全部正确返回了，也只显示了前几个。
