### ISSUE TITLE
Exception: TypeError: Illegal constructor

### ISSUE THREAD

**Issue by oycol** [gxvv/ex-baiduyunpan#234]
Exception: TypeError: Illegal constructor

Script Ver: 1.0.3

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by JYeung111** [comment]
X3998 ：
你用的是外間的複印版，源自原作 v0.2.2，如有問題要向該版求救，

BaiduPan Explorer
https://greasyfork.org/zh-TW/scripts/39844

這是原作區，不會處理這些問題！

**Comment by oycol** [comment]
好的,谢谢,能用了
