### ISSUE TITLE
worn

### ISSUE THREAD

**Issue by plqkssst** [gxvv/ex-baiduyunpan#235]
Exception: TypeError: Illegal constructor

Script Ver: 0.2.2.Mod

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by JYeung111** [comment]
你用的是外間的複印版，源自原作 v0.2.2，如有問題要向該版求救，

EX-百度云盘去加载提示版
https://greasyfork.org/zh-TW/scripts/39854

這是原作區，不會處理這些問題！
