### ISSUE TITLE
Vivaldi浏览器下无法加载插件

### ISSUE THREAD

**Issue by 7mm** [gxvv/ex-baiduyunpan#236]
Win10系统，在Vivaldi浏览器（Chrome内核）下，使用Tampermonkey扩展，这个插件总是无法加载显示，不知道有没有其他人遇到过~但是在Macos下使用Vivaldi浏览器就没问题，所有插件都是一致的，这个问题很头疼。

**Comment by gxvv** [comment]
> 仅对最新版 Chrome 和 Safari 浏览器下 TamperMonkey 提供支持。
