### ISSUE TITLE
你好，请问一下什么是外间的复印版？我也遇到illegal constructor的问题

### ISSUE THREAD

**Issue by BrentCC** [gxvv/ex-baiduyunpan#239]
Exception: TypeError: Illegal constructor

Script Ver: 0.2.2.Mod

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by JYeung111** [comment]
复印版這個名似是我叫的，意思是指那些腳本百分百抄襲，或只作無意義的改動例如名稱，備註(remark)，提示等等，對腳本功能無實質改良提升，更無支援(support)，即是翻版，Ａ貨的好聽的稱號，
用家遇到問題只會找原作者求救，而不是發放复印版的人，閣下便是一個活生生的例子。
再者外間亦會被誤導此作品是复印者的原作，更是被多個論壇介紹及推介，是否公道，合理嗎？

 BrentCC 所用的版本就是复印版
名稱 ： EX-百度云盘去加载提示版
作者 ：  yi ming
版本 ：  0.2.2.Mod

這是只删除部份備註和腳本起動時的提示而已！
