### ISSUE TITLE
downloadManager.js加载失败

### ISSUE THREAD

**Issue by Zoey-zheng** [gxvv/ex-baiduyunpan#241]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by fenwickxie** [comment]
Exception: downloadManager.js加载失败
Script Ver: 0.2.1
TemperMonkey Ver: 4.8.5847
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
