### ISSUE TITLE
多次点击下载后，百度出现验证码。这时，在点击ex复制链接，还没输入完百度验证码，ex不显示复制链接

### ISSUE THREAD

**Issue by NxGreen** [gxvv/ex-baiduyunpan#244]
多次点击下载后，百度出现验证码。这时，在点击ex复制链接，还没输入完百度验证码，ex不显示复制链接

**Comment by gxvv** [comment]
如果出现验证码，就不能批量下载，只能单个下载。

因为每个请求都要输入验证码，不支持逐个输入验证码。

**Comment by shewayjutest** [comment]
無法取得連結，輸入驗證碼後，出現取得連結失敗訊息

**Comment by gxvv** [comment]
@shewayjutest 
当前需要先登录才能获取到链接，百度的限制
