### ISSUE TITLE
不登錄不能下載新限制

### ISSUE THREAD

**Issue by JYeung111** [gxvv/ex-baiduyunpan#245]
昨日証實不登錄不能下載的限制，不登錄是不會有完整的回應，而會導腳本無法顯示结果，今日已有獨立程式可以破解，好似話改變百度的接口和参數；但因不開放源碼和全用 https (443) request，無法學習，不知版主是否有相关方法和資訊？

**Comment by gxvv** [comment]
服务器限制我是没法解决的，既然百度在做这方面的限制，有方法也不会长久的，等稳定些再看看吧。:sweat_smile:

**Comment by JYeung111** [comment]
我發現有人用一個不正道的方法，就是用別人做替身進行下載，這個方早前曾做個實驗，是成功的！當時感到無實質意義，放棄了！今早已有人加此入專用腳本！不過人人用此替身，會否令替身很快就死亡？
不過我平時都很少用隱身下載，只是好奇心大吧！

**Comment by gxvv** [comment]
流量太大了就算是会员也会限速吧，这也是百度的限制了。

模拟登录的话应该是改写 Cookie 吧，能不能把可用的脚本链接发来，研究研究。

**Comment by JYeung111** [comment]
是改写 Cookie ；
我已將修改方法私信到 gxvv  https://greasyfork.org
因我用的Ex版是經我自行修改，混雜很多測試碼，很雜亂，所以另做一個整潔版適合原作，原理已確証有效，但句法可能有錯，見諒！

**Comment by gxvv** [comment]
已查收，方法了解了。但这个 Cookie 中应该包含了用户信息，同一个 Cookie 应该不适合多人同时使用吧。

**Comment by JYeung111** [comment]
Cookie 中是包含了用户信息，只要合式工具，可直接以此cookie 進行登錄，不需登入名和密碼，所以我叫它做替死鬼方法，百度認為有人濫用時，只會怪罪此cookie内藏的户口人！
以我理解百度是每次收到request 才用cookie作一次性檢查，次次獨立，不會長期連接，因此同一个 Cookie 應可適合多人同时使用，除非有發生特殊性的相衝，稍後一些時日便知！

**Comment by gxvv** [comment]
不是说不能用，只是多人使用会更快被认为是在滥用吧。

**Comment by JYeung111** [comment]
我同意，如多人瘋狂使用，就會引發百度注意，不知否這原因，另一個非開源程式，可以免錄下載功能，修正發佈後，不需一天已失效！

**Comment by JYeung111** [comment]
百度又有新招了：
百度云升级
亲，百度网盘正在升级中……给你带来的不便敬请谅解，我们稍候就回来

今次不知有甚麽新限制？？？

**Comment by la5939** [comment]
不知道有没有用， 下面这个百度网盘个人专辑，无需登录  也不需插件，可以直接复制链接下载
https://pan.baidu.com/pcloud/album/info?uk=774231536&album_id=2406280569414701975

**Comment by JYeung111** [comment]
百度新招：
初步測試在结果
    是百度不再接受使用Browser(火狐)在自己盤直接進行下載！
新限制應該是針對代理名，這新招只會使用腳本用家才有影响，對於程式用家無影响，因的它們一向都仿冒百度管客户端代理名，看來我又要修改腳本應對。

**Comment by yichangshengwu** [comment]
然而，火狐 和 vivaldi 上都不灵了。。。

**Comment by sungarda** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.7.63

UA: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.6821.400 QQBrowser/10.3.3040.400

**Comment by JYeung111** [comment]
早前己發現有破解，之後又被封殺，今天偶然性發現又有破解之法！
因此都是关閉此題算了
