### ISSUE TITLE
11月５日昨夜百度好似又再有新的改動，又是針對分享盤單文件下載(403)，全面封殺破解

### ISSUE THREAD

**Issue by JYeung111** [gxvv/ex-baiduyunpan#253]
新的改動是百度分享盤的單一文件下載方式！
以前是不需身份核証就可以下載，現在已和在身自己盤單文件下載統一化，不能簡單用复制下載，必需先進行身份核證才會真正下載地址，暫時已有方法突破，但不知何時會失效！

**Comment by darkness-y** [comment]
目前即使登陆后获取到的下载链接，尝试使用axel工具或者迅雷等，都出现403的情况

**Comment by JYeung111** [comment]
昨夜百度好似又再有新的改動，又是針對分享盤單文件下載， 最新破解即刻玩完，累街坊！

誰叫有些人玩高調散佈，人地加限，你就立即高調公佈突破方法，即係擺明車馬和人地玩，百度怎會不即刻回招！

**Comment by NanaseRuri** [comment]
现在只能下载单个文件以及现在下载速度也被下调至100k左右，以及大概下载三小时会断（虽然以前也是会断），即是说现在idm撑死只能龟速下载1-2g

**Comment by woeijiunn88** [comment]
现在只能暂时用雷云一个一个下载了
脚本可以说是失效了，被限制线程数和100k难受

**Comment by deorth-kku** [comment]
IDM开高级浏览器集成和浏览器自带还能下载，其它方法全都403。IDM也就不到200k，感觉GG
