### ISSUE TITLE
下载无反应

### ISSUE THREAD

**Issue by zeroNIz** [gxvv/ex-baiduyunpan#257]
点击下载一直转圈，idm和chrome都没有弹出下载
复制链接报错400 bad request

**Comment by JYeung111** [comment]
先講清楚
是分享盤還是自己盤，
是單一文件下載還是其他？

**Comment by zeroNIz** [comment]
不論是單一還是多個文件都是這樣，自己盤

**Comment by JYeung111** [comment]
百度自己盤 
A. 單件下載鏈 
    需要身份核實和用户代理的限制(新加)
B. 多個文件或含有文件夾 的下載鏈。
    有上限 ~300M 總壓縮容量的限制

**Comment by zeroNIz** [comment]
所以有解決辦法麽？？

**Comment by JYeung111** [comment]
解决方法有多種，而在百度自己盤下載的方法會較為複雜，
不過你太遲，此 case support 已完结！
