### ISSUE TITLE
報告一些問題

### ISSUE THREAD

**Issue by VOIA14** [gxvv/ex-baiduyunpan#258]
直鏈下載時，貌似只對小文件下載有效。具體文件的大小在多少一下適用暫未明確。
ex外鏈下載，使用idm下載直鏈，顯示無權限。
ex壓縮外鏈下載，idm同時下載上限數量為3個。
不清楚這些是個人獨遇到的問題，還是普遍都存在。

**Comment by VOIA14** [comment]
以及無法壓縮-外鏈下載文件夾呢。

**Comment by gxvv** [comment]
服务端限制，选择的文件数量大小超过限制均无法下载
