### ISSUE TITLE
2018/10/31 日开始，正常下载可以，但一旦启用插件就会HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by Sam0230** [gxvv/ex-baiduyunpan#259]
2018/10/31 日开始，正常下载可以，但一旦启用插件就会HTTP/1.1 403 Forbidden（没有权限下载），不管是直接下载，复制链接，复制压缩链接都一样，链接放到Chrome 浏览器，IDM，迅雷中都一样。我估计百度可能改了链接请求方式。

**Comment by QieSen** [comment]
遇到相同情况，无论是复制链接还是复制压缩连接都无法在IDM下载。

**Comment by gxvv** [comment]
不用插件正常下载只能下载小文件，用了插件获取的链接不一定能下载，有服务端限制

可能的原因
- 选择的文件大小数量超过限制
- 文件下载需要携带 Cookie 信息
