### ISSUE TITLE
现在只有普通下载功能了吗？

### ISSUE THREAD

**Issue by lweo** [gxvv/ex-baiduyunpan#26]
第一次使用，只看到了普通下载链接。。

**Comment by gxvv** [comment]
什么浏览器？

**Comment by lweo** [comment]
@gxvv  chrome

**Comment by gxvv** [comment]
chrome 65，TamperMonkey 4.5 正常。

更新浏览器、TamperMonkey和脚本，并关闭其他脚本，清空缓存再试下。
