### ISSUE TITLE
加载页面就会弹出

### ISSUE THREAD

**Issue by jianweigit** [gxvv/ex-baiduyunpan#271]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 2.9.10

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by boomyyyy** [comment]
+1
