### ISSUE TITLE
"开始请求链接"等待时间太短

### ISSUE THREAD

**Issue by GNDC** [gxvv/ex-baiduyunpan#274]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.

[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed
下载的多了，再用插件“复制链接”什么的时候百度会让输入验证码，而“开始请求链接”等待时间太短，还没等验证码输好就都一闪而过了。。。

**Comment by gxvv** [comment]
验证码只能在单文件时输入，多文件无法输入
