### ISSUE TITLE
无法下载文件

### ISSUE THREAD

**Issue by Iammyself001** [gxvv/ex-baiduyunpan#275]
无法下载此文件。
备注: HTTP/1.1 400 Bad Request

**Comment by Iammyself001** [comment]
你好，我已经更新到最新的版本，可是为什么还是会出现无权限下载的问题，是需要怎么设置呢？

**Comment by bloodsucker3011** [comment]
hi sorry im not speech chinese , and thank you for you work

i recent have same problem after i download first file 
and the speed is real slow 9~60 kb/sec

and it start happen yesterday 25/12/2018

**Comment by gxvv** [comment]
文件过大或需要登录，无法解决

The speed is limited by server side, this script can't fix it. @bloodsucker3011
