### ISSUE TITLE
EX-baiduyunpan: 插件加载成功，按钮初始化失败

### ISSUE THREAD

**Issue by Herycdd** [gxvv/ex-baiduyunpan#276]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.

[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed

**Comment by 32103210** [comment]
我应该也碰到同样的问题了，插件安装成功，但是在共享盘以及个人盘上都没有显示“ex-下载”这个按钮出现了？是作者停止这个脚本的更新了吗？

**Comment by gxvv** [comment]
更新脚本，使用 Chrome + TamperMonkey，关闭其他百度云插件重试
