### ISSUE TITLE
出现“EX-baiduyunpan：正在开始下载... ” 的窗口，加载几秒后窗口消失，没有显示下载页面

### ISSUE THREAD

**Issue by Max-Lv6** [gxvv/ex-baiduyunpan#279]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.

[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed

**Comment by gxvv** [comment]
这个文件过大，不能直接下载，也不能复制链接下载
