### ISSUE TITLE
复制链接用IDM下载，Bad Request!

### ISSUE THREAD

**Issue by Charles-Kai** [gxvv/ex-baiduyunpan#283]
# 提交 Issue 前，请[查看][1]是否有相同的 Issue，重复问题直接关闭。

# Before you submit an Issue, please [check][1] the Issues posted. Duplicate Issues will be closed directly.

[1]: https://github.com/gxvv/ex-baiduyunpan/issues?q=is%3Aissue+is%3Aclosed

**Comment by alexyau19980501** [comment]
https://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B%22644988888128527%22%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:M4iY3Ez2P7UJO8gZBjFiq0saxMI%3D&uid=4280026072&time=1552540893&dp-logid=529871898363919845&dp-callid=0&shareid=2622712978&from_uk=4280026072&zipname=%E3%80%90%E6%96%87%E4%BB%B6%E5%A4%B9%E3%80%91BOOTLEG.zip

**Comment by huanghe2015** [comment]
这问题无解。。
