### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by fajiayu** [gxvv/ex-baiduyunpan#284]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.8

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by 55cc** [comment]
相同问题
具体原因 This request has been blocked; the content must be served over HTTPS.

详细如下:
mod_455fd55.js:1 Mixed Content: The page at 'https://pan.baidu.com/disk/home?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#/all?path=%2F&vmode=list' was loaded over HTTPS, but requested an insecure script 'function-widget-1:download/service/downloadManager.js'. This request has been blocked; the content must be served over HTTPS.
r @ mod_455fd55.js:1
t @ mod_455fd55.js:1
s @ mod_455fd55.js:1
require.async @ mod_455fd55.js:1
e.async @ boot.js?t=1554346354077:1
(anonymous) @ userscript.html?id=8660b81a-39a6-4eea-8715-f9597af323d1:324
(anonymous) @ userscript.html?id=8660b81a-39a6-4eea-8715-f9597af323d1:320
require @ mod_455fd55.js:1
(anonymous) @ userscript.html?id=8660b81a-39a6-4eea-8715-f9597af323d1:378
tms_8660b81a_39a6_4eea_8715_f9597af323d1 @ userscript.html?id=8660b81a-39a6-4eea-8715-f9597af323d1:380
(anonymous) @ VM991:2
(anonymous) @ userscript.html?id=8660b81a-39a6-4eea-8715-f9597af323d1:4
(anonymous) @ userscript.html?id=8660b81a-39a6-4eea-8715-f9597af323d1:5
(anonymous) @ userscript.html?id=8660b81a-39a6-4eea-8715-f9597af323d1:382
(anonymous) @ VM991:2
E_c @ VM991:3
ia @ VM997:63
create @ VM997:75
c @ VM997:16
runListeners @ VM997:16
(anonymous) @ VM997:76
W @ VM991:10
e @ content.js:6
send @ content.js:8
(anonymous) @ content.js:27
processQueue @ content.js:3
a @ content.js:10
mod_455fd55.js:1 Mixed Content: The page at 'https://pan.baidu.com/disk/home?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#/all?path=%2F&vmode=list' was loaded over HTTPS, but requested an insecure script 'function-widget-1:download/service/downloadDirectService.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by halton** [comment]
Is this issue fixed?

I still have this issue on my Chrome 77.

```
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.8.41

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3835.0 Safari/537.36
```
