### ISSUE TITLE
百度云直接报错

### ISSUE THREAD

**Issue by cuianbing** [gxvv/ex-baiduyunpan#305]
```
Exception: downloadManager.js加载失败
Script Ver: 0.2.1
TemperMonkey Ver: 4.8.41
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
```

**Comment by Gxz-NGU** [comment]
EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.8.41

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
