### ISSUE TITLE
程序异常

### ISSUE THREAD

**Issue by onlyone1996wj** [gxvv/ex-baiduyunpan#310]
Exception: Error: Cannot find module `system-core:context/context.js`

Script Ver: 1.0.3

TemperMonkey Ver: 4.8.5847

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by zwh-eric** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.0

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
