### ISSUE TITLE
Expection: downloadManager.js加载失败

### ISSUE THREAD

**Issue by Gasoonjia** [gxvv/ex-baiduyunpan#314]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.8.41

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Comment by yanwei1983** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.8.41

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
