### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by niannings** [gxvv/ex-baiduyunpan#319]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.8.41

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by jiang-anwei** [comment]
相同问题

**Comment by feibaliang** [comment]
这个有解决的办法吗？

**Comment by edwinhuish** [comment]
+1 相同的问题
