### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by IT-lxc** [gxvv/ex-baiduyunpan#341]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.9.6095

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

**Comment by GLWJ** [comment]
EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.9

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
