### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by xiaohu95271** [gxvv/ex-baiduyunpan#347]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.9

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

**Comment by dalilll** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.1

TemperMonkey Ver: 4.9

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
