### ISSUE TITLE
分享的链接失效后,打开页面报错

### ISSUE THREAD

**Issue by leon0516** [gxvv/ex-baiduyunpan#4]
Win10平台 Chrome版本 58.0.3029.96 (64-bit)

EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue
Exception: downloadManager.js加载失败
Script Ver: 0.1.6
TemperMonkey Ver: 4.2.7
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by gxvv** [comment]
这个页面报错确实存在，但不会妨碍正常使用

下个版本屏再蔽掉这个页面上的错误吧
