### ISSUE TITLE
22/03/2018 今天百度云代码更新了，脚本失效，修改中，重复Issue downloadManager.js加载失败 请不要提交了

### ISSUE THREAD

**Issue by gxvv** [gxvv/ex-baiduyunpan#44]

**Comment by xman55555** [comment]
同求原因,一直保错,!不知道为什么,大佬呢?
EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
