### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by JasonLeemz** [gxvv/ex-baiduyunpan#50]
Exception: downloadManager.js加载失败

Script Ver: 0.1.8

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by luvletter1205** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.1.5248

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

同样

**Comment by ANANA** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
