### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by jeffsun0227** [gxvv/ex-baiduyunpan#51]
Exception: downloadManager.js加载失败
Script Ver: 0.2.0
TemperMonkey Ver: 3.9.202
UA: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by RonnyHuang** [comment]
百度云更新代码了 等下一波技术吧

**Comment by jiaochenglong** [comment]
嗯，我也是发现新版本出现的
