### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by wanggan768q** [gxvv/ex-baiduyunpan#53]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.
请尝试更新脚本或复制以下信息提交issue
Exception: downloadManager.js加载失败
Script Ver: 0.2.0
TemperMonkey Ver: 4.5
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by wqk317** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3377.0 Safari/537.36

**Comment by XiaoXiaoYanHe** [comment]
和楼上一模一样

**Comment by tea1111980** [comment]
**#EX-baiduyunpan:程序异常**

Exception: downloadManager.js加载失败

Script Ver: 0.1.8

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by ugksoft** [comment]
和楼上一样,!!!!

Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.100 Safari/537.36

**Comment by Lsdixin** [comment]
一样的。
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
