### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by yonnywei** [gxvv/ex-baiduyunpan#55]
EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by SherlockGougou** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.6.5741

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by jingx15** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by Charelyz** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.0

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

**Comment by coolingx** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.6.5709

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by liA-siran** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by Runnlin** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by demon-zhonglin** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
