### ISSUE TITLE
downloadManager.js加载失败

### ISSUE THREAD

**Issue by yans006** [gxvv/ex-baiduyunpan#59]
EX-baiduyunpan:程序异常

请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.6.5709

UA: Mozilla/5.0 (Windows NT 10.0; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by MaxMadcc** [comment]
![qq](https://user-images.githubusercontent.com/19978097/37808588-1c55cd0e-2e86-11e8-8934-0404fa2390d2.png)
百度自己把文件给弄没了
