### ISSUE TITLE
批量获取链接的时候需要输入验证码 超时时间太短

### ISSUE THREAD

**Issue by a89910911** [gxvv/ex-baiduyunpan#6]
版本0.1.6 代码191行 建议把 超时时间从3000改为12000
我自己改了本地的 时间足够

**Comment by gxvv** [comment]
在存在文件夹和文件混合批量获取链接时，会存在些问题

**Comment by gxvv** [comment]
在存在文件夹和文件混合批量获取链接时，会存在些问题

出现验证码的话，推荐先保存到自己的网盘，再进行下载，或者换个时间进行批量复制，或者使用普通下载。
