### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by small-bao** [gxvv/ex-baiduyunpan#60]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by lsp84ch83** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
