### ISSUE TITLE
是不是又挂了？

### ISSUE THREAD

**Issue by RonnyHuang** [gxvv/ex-baiduyunpan#64]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.

**Comment by gxvv** [comment]
请提供更多信息

**Comment by ohmytime** [comment]
你好, MacBook 上的Chrome, 我估计是升级到最新Chrome所导致的.

<img width="563" alt="002" src="https://user-images.githubusercontent.com/490477/37871413-d503b0ec-301f-11e8-95b4-71e54c40e612.png">
<img width="682" alt="003" src="https://user-images.githubusercontent.com/490477/37871409-c4d55b26-301f-11e8-80d8-d93385ab2dd8.png">

**Comment by RonnyHuang** [comment]
没挂，原来是我的百度云账号被黑名单了
悲剧

**Comment by ohmytime** [comment]
楼上的干了什么,导致你的账号被黑名单了?

**Comment by RonnyHuang** [comment]
看了很多帖子，觉得和网盘里的内容没多大关系，应该是使用了第三方百度网盘软件突破网速之类的原因，我用过山寨云...也有可能是直链IDM被检测到的原因。
我在PC上用IDM下载直链，手机上用ADM下载山寨云的直链。速度都基本可以达到带宽满速
现在我网盘里的任何文件不能以任何方式下载（可以分享、图片可以查看）
总之，慎重使用吧

**Comment by gxvv** [comment]
@ohmytime 更新脚本

**Comment by RonnyHuang** [comment]
哈，申诉了一下解封了竟然
