### ISSUE TITLE
添加迅雷链接代码是否可合并

### ISSUE THREAD

**Issue by haiifenng** [gxvv/ex-baiduyunpan#65]
你好，之前讨论过这个迅雷链接的问题。发现新版本代码进行了优化处理，方便扩展，我按照之前的思路增加了迅雷链接，是否可以提交到源码中呢？

**Comment by gxvv** [comment]
你可以fork一份代码，单独发布一份

**Comment by haiifenng** [comment]
Greasy Fork的脚本需要处理吗？还是我自己创建一个脚本自己用？

**Comment by gxvv** [comment]
你可以在Greasy Fork发布一份
