### ISSUE TITLE
can't use

### ISSUE THREAD

**Issue by 359075391** [gxvv/ex-baiduyunpan#66]
Exception: downloadManager.js加载失败
Script Ver: 0.1.7
TemperMonkey Ver: 4.5
UA: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by unblockiqiyi** [comment]
把腳本更新到0.2.1即可修復此問題
