### ISSUE TITLE
重复的EX-下载按钮

### ISSUE THREAD

**Issue by ericbrownz** [gxvv/ex-baiduyunpan#68]
![63](https://user-images.githubusercontent.com/34184767/38229062-5d77452c-3739-11e8-8985-62261ff4e384.png)

选择一个文件之后会出来两个EX-下载按钮

**Comment by gxvv** [comment]
刷新之后也这样吗？我没有这个问题，是不是安装多个百度云插件？

**Comment by EricBrownz** [comment]
禁用另一个之后刷新依然会出现😂
![64](https://user-images.githubusercontent.com/34184767/38237744-967d1e3e-375a-11e8-92d0-7aa51b7d4020.png)

**Comment by gxvv** [comment]
无法重现这个问题😕，chrome，tampermonkey，脚本都是最新版吗？

**Comment by alexya** [comment]
@gxvv 
I can repro the issue too. 
这是没有任何文件被选中时：
![image](https://user-images.githubusercontent.com/2831220/38294882-f6614036-381e-11e8-8a40-09e50a82c7f9.png)

这是有一个文件被选中时：
![image](https://user-images.githubusercontent.com/2831220/38294906-02738226-381f-11e8-93dc-5657f34af757.png)

当然，不影响使用，还是可以拿到文件下载链接的。
![image](https://user-images.githubusercontent.com/2831220/38294989-3532a71e-381f-11e8-9ae5-44fbe82d0cee.png)

**Comment by alexya** [comment]
@EricBrownz 
你另外一个插件，“百度网盘高速下载助手”使用下来如何？

**Comment by gxvv** [comment]
我也重现了，屏幕分辨率较高时会有两个按钮。

**Comment by gxvv** [comment]
我也重现了，屏幕分辨率比较高的时候会有两个按钮。

**Comment by EricBrownz** [comment]
@alexya 一般吧 
说实话后来我还是只用百度自己给的链接，只不过我下的文件特别多，分很多文件夹下的，虽然单文件限速，但是总的加起来还是可以跑到带宽一半多。
插件获取的直链经常被百度关闭（http错误/坏请求/远程链接已关闭。。。）重下，百度吃相难看。

**Comment by DaPangR** [comment]
我也发现了这个问题
这是没有选中任何文件的时候
![1](https://user-images.githubusercontent.com/7512488/41279600-8676e92a-6e5f-11e8-8bed-0ac8df9b1108.PNG)

点击之后，显示
![2](https://user-images.githubusercontent.com/7512488/41279612-8df372ea-6e5f-11e8-84d3-0ad9b9a22155.jpg)
选中一个文件之后，出现两个“EX-下载”
![3](https://user-images.githubusercontent.com/7512488/41279649-a896ca5c-6e5f-11e8-9a66-0eeaf98ebcdb.jpg)
这个可以修复吗
