### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KurokiK** [gxvv/ex-baiduyunpan#69]
Exception: downloadManager.js加载失败
Script Ver: 0.1.7
TemperMonkey Ver: 4.5
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by ainuoyan** [comment]
Exception: downloadManager.js加载失败

Script Ver: 2018.04.04_0.2.1.Mod

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
