### ISSUE TITLE
插件安装后，不能下载

### ISSUE THREAD

**Issue by wangwenfan** [gxvv/ex-baiduyunpan#7]
下载百度云盘里的东西，下载方式还是和以前一样，使用浏览器自带的下载工具，但是刷新页面，提示插件加载成功。点击下载不显示下载插件。用的chrome浏览器。

**Comment by gxvv** [comment]
chrome v58 64bit、TamperMonkey v4.3.6、win7 64bit、脚本v0.1.6正常。

请先关闭其他插件，脚本，清空浏览器缓存，更新插件脚本后重试一下。

我看了下网盘首页，分享页面，都是正常的，请提供下是哪个页面出的问题。
