### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by baibai-lee** [gxvv/ex-baiduyunpan#75]
Exception: downloadManager.js加载失败
Script Ver: 0.1.7
TemperMonkey Ver: 4.0.69
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.4549.400 QQBrowser/9.7.12918.400

**Comment by unblockiqiyi** [comment]
把腳本更新到0.2.1

**Comment by gxvv** [comment]
Fixed #63
Closed #75

**Comment by baibai-lee** [comment]
现在可以了，十分感谢
