### ISSUE TITLE
Ver: 0.2.1 Exception: TypeError: Illegal constructor 点复制连接时出错

### ISSUE THREAD

**Issue by sweepdoff** [gxvv/ex-baiduyunpan#77]
Exception: TypeError: Illegal constructor

Script Ver: 0.2.1

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3371.0 Safari/537.36

**Comment by sweepdoff** [comment]
这几天都试了，，情况没变，，

**Comment by gxvv** [comment]
把控制台报错的图贴一下
