### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by s-bat** [gxvv/ex-baiduyunpan#79]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.
Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.0.69

UA: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by gxvv** [comment]
Fixed #63
