### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by afserusa** [gxvv/ex-baiduyunpan#86]
Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

安装后遇到这样的问题。

**Comment by gxvv** [comment]
Duplicate of #63
