### ISSUE TITLE
Exception: downloadManager.js加载失败Script Ver: 0.2.1

### ISSUE THREAD

**Issue by dearqiangda** [gxvv/ex-baiduyunpan#87]
Exception: downloadManager.js加载失败
Script Ver: 0.2.1
TemperMonkey Ver: 4.5
UA: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

请尝试更新脚本或复制以下信息提交issue
Exception: downloadManager.js加载失败
Script Ver: 2018.04.04_0.2.1.Mod
TemperMonkey Ver: 4.5
UA: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by gxvv** [comment]
清理缓存后再试下
