### ISSUE TITLE
下载文件大小都是1MB左右 怎么回事？

### ISSUE THREAD

**Issue by 244276041** [gxvv/ex-baiduyunpan#88]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.
下载的文件怎么是1.几MB    下很多文件都是这样。。为什么啊？

**Comment by gxvv** [comment]
> 本脚本仅提供了获取下载链接的功能，下载速度过慢/第三方下载工具不能下载/链接超时/压缩包不能解压等问题与脚本无关。

换个下载器试试
