### ISSUE TITLE
 downloadManager.js加载失败

### ISSUE THREAD

**Issue by chen1136a** [gxvv/ex-baiduyunpan#9]
Exception: downloadManager.js加载失败
Script Ver: 0.1.7
TemperMonkey Ver: 4.3.6
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by gxvv** [comment]
win7未能重现，请提供更多信息（网盘主页还是分享页，控制台报错信息）

**Comment by chengzx** [comment]
偶尔出现这个错误，刷新几次就可以正常加载

**Comment by gxvv** [comment]
@chengzx 也是win10吗，具体在哪个类型的页面发生的？
