### ISSUE TITLE
插件已经失效，请大大帮助看一下

### ISSUE THREAD

**Issue by zcy85611** [gxvv/ex-baiduyunpan#91]
今天尝试用获得链接下载的时候，已经无法下载了

百度网盘最近有更新，请大大帮助看下是否这个插件需要修改，谢谢

**Comment by gxvv** [comment]
我这是好的，提供下浏览器、脚本、插件版本

**Comment by themostfreeboy** [comment]
我今天用也不好使，浏览器google 67.0.3396.18（正式版本）（64 位），插件版本Tampermonkey v4.0.69版，脚本0.1.7版，不过在250行
onClose: function() {
                                clipboard && clipboard.destory && clipboard.destroy();
                            }
此段代码的clipboard.destroy()括号处报错，"Excepted an assignment or function and instead saw an expression"，大神看一眼此处代码怎么修改，谢谢。

**Comment by themostfreeboy** [comment]
我这边第一次试的时候确实有点问题，具体情况：浏览器：google 67.0.3396.18（正式版本）（64 位），插件Tampermonkey v4.69版，脚本版本，目前master分支最新版0.20 0.21，具体问题出现在EX-baiduyunpan.user.js文件中的282行的onClose: function()代码里，具体报错为"Expected an assignment or function call and instead saw an expression"，大意就是此处需要一个具体的，而不是表达式，我将这部分代码直接return(……)，但是可能返回值的逻辑或者是否返回有问题，后来就这这个值临时赋值给一个不用的临时变量就可以了，就是在这行之前加一个"var temp = "就行了，把那个表达式的值赋值给一个不用的临时变量temp就可以了。个人感觉这个有可能是脚本语法的标准不同，稍微改一下就可以用了。
另外本人可能没有使明白，master分支一共有两个脚本，EX-baiduyunpan.mock.js和EX-baiduyunpan.user.js，当我把两个脚本放一起的时候，会出现脚本加载成功但是按钮初始化失败的情况，我没有具体看代码，有可能函数冲突等等，也有可能脚本我没有具体理解其含义。当只用EX-baiduyunpan.user.js脚本内容，且将上述问题修复后，可以正常使用，已经从百度云通过此脚本提取出连接用迅雷下载中。。。此bug可以修正一下。

**Comment by gxvv** [comment]
@themostfreeboy 

这个表达式不改没关系的，只是`TamperMonkey`不推荐这样写，关掉语法检查就没这个提示了。

`mock.js`是用来模拟数据的，方便修改脚本时调试。不要合并两个脚本都是单独安装的。

**Comment by themostfreeboy** [comment]
@gxvv 
了解了，谢谢。

**Comment by bao3** [comment]
我这里是好的。
