### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by yilvqingfeng** [gxvv/ex-baiduyunpan#92]
Exception: downloadManager.js加载失败
Script Ver: 2018.04.04_0.2.1.Mod
TemperMonkey Ver: 2.8.4
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36 Maxthon/5.2.1.6000

**Comment by blurHY** [comment]
Exception: downloadManager.js加载失败
Script Ver: 0.1.8
TemperMonkey Ver: 4.6.5757
UA: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0
