### ISSUE TITLE
百度云提示插件异常，麻烦帮忙看看

### ISSUE THREAD

**Issue by hellohello890** [gxvv/ex-baiduyunpan#94]
# 提交Issue前，请查看是否有相同的Issue，重复问题直接关闭。

# Before you submit an Issue, please check the Issues posted. Duplicate Issues will be closed directly.

打开百度云网页版之后，自动弹出一下信息（Windows10   360浏览器，插件更新显示无更新）

EX-baiduyunpan:程序异常
请尝试更新脚本或复制以下信息提交issue
Exception: downloadManager.js加载失败
Script Ver: 0.1.7
TemperMonkey Ver: 4.0.69
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
关闭

**Comment by hellohello890** [comment]
版本为0.1.7  ，麻烦大神帮忙看看什么原因，谢谢

**Comment by gxvv** [comment]
Duplicate of #63
