### ISSUE TITLE
浏览器加载插件失败

### ISSUE THREAD

**Issue by wyuf1988** [gxvv/ex-baiduyunpan#95]
Exception: downloadManager.js加载失败
Script Ver: 0.1.6
TemperMonkey Ver: 4.5
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

麻烦大神看一下是什么情况，谢谢了

**Comment by gxvv** [comment]
Duplicate of #63
