### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by sjzsjzsjz** [gxvv/ex-baiduyunpan#99]
Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by rzr00** [comment]
Exception: downloadManager.js加载失败

Script Ver: 0.1.7

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
